export const CONFIG = {
    WINDOW_WIDTH: 800,
    WINDOW_HEIGHT: 600,
    WINDOW_MOVE_STEP: 100,
    WINDOW_MOVE_STIFFNESS: 0.26,
    WINDOW_MOVE_DAMPING: 0.64,
    WINDOW_MOVE_VELOCITY_EPSILON: 0.25,
    WINDOW_MOVE_POSITION_EPSILON: 0.35,
    WINDOW_MOVE_TICK_MS: 16,
    GEMINI_MODEL: 'gemini-2.5-flash',
    MAX_SCREENSHOTS: 5,
    DEFAULT_LANGUAGE: 'Python',
    PROMPT_MODES: ['code', 'mcq'],
    DEFAULT_PROMPT_MODE: 'code'
};
